---
title: "構造的因果モデルの基礎 輪読"
subtitle: "第3章 因果ダイアグラムの基礎"
author: "Reiji Konishi"
date: "2020/8/13"
output:
  revealjs::revealjs_presentation:
    df_print: "paged"
    css: "for_revealjs.css"
    self_contained: true
#    transition: convex
    theme: sky
    highlight: kate
    center: true
    reveal_plugins: ['chalkboard']
    
    reveal_options:
      slideNumber: 'c/t'
      chalkboard:
        theme: whiteboard
        
pandoc_args: [
      '--from', 'markdown+autolink_bare_uris+tex_math_single_backslash-implicit_figures'
    ]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      comment = "",
                      fig.height = 10,
                      fig.width = 10,
                      out.height = 300,
                      out.width = 300)
options(dplyr.print_max = 1e9)
```

# 因果関係の頑健性 {#robustness}

## 因果とデータ生成過程 {#causality_data_generating_process}

* ベイジアンネットワーク
  * 統計的な独立関係を記述するツール
  * 必ずしも因果関係を意味しない
  * 任意の変数順序で逐次的に因数分解可能(2.36式)
  * しかし、因果的な解釈をすることも…
  
* 因果関係(データ生成過程)は普遍的
  * それ故、有向グラフに普遍的で説得力のある解釈を与えようとしてしまう
  * 事前知識(肌感)とデータから導かれる統計的な独立関係が合うかどうかで判断しがち
  
* 因果関係を物理的なデータ生成過程として捉えて、その視覚的表現である因果ダイアグラムについて解説


# 因果ダイアグラム {#causal_diagram}

## 定義(因果ダイアグラム) {#definition}

<div class="box">
DAG $G$とその頂点に対応する確率変数の集合$\mathbf V = \{X_1, \dots, X_p\}$

グラフ$G$が確率変数間の関数関係を以下の形で規定し、
確率変数がこの関数関係に従って自律的でかつ定常的に生成される時、
DAG $G$は因果ダイアグラムという

$$
X_i = g_i(\text{pa}(X_i), \epsilon_i), \quad i = 1, \dots, p \tag{3.1}
$$
</div>

* 錯乱項$\epsilon_i$は互いに独立
* 自律的 P6
  * モデルの方程式の一部が変化しても、他の構造には影響を与えない
* 定常的 P75(後述)
  * データ生成過程が客観的な知識に基づいて記述されたもので、人間の主観的な認識ではないこと
* $\text{pa}(X_i)$は$X_i$の直接的原因
* 3.1式のモデルはデータ生成過程の正確な記述ではなく**近似**


## 考察(錯乱項の独立性) {#discssion1}

* 因果ダイアグラム上の変数$\mathbf V$に含まれる要素が観測可能であるかどうかは定義に含まれていない
  * 観測できる変数もできない変数も全部書き表す必要がある

* 因果ダイアグラムの定義は、6章の構造的因果モデルとは若干異なる
  * 因果ダイアグラム:錯乱項$\epsilon_i$は互いに独立と仮定(マルコフ的)
  * 一般的な構造的因果モデルは錯乱項が独立でなくてもOK(セミ・マルコフ的)

* 錯乱項同士が従属だと、双方向矢線で結ぶ
  * 例えば、$\epsilon_i$と$\epsilon_j$が従属する場合
  
$$
X_i \longleftrightarrow X_j
$$

* 錯乱項どうしの独立関係を担保するため、潜在変数$U$を用いて表現することも
  * $U$は、双方向矢線を構成する非観測変数の集合を代表したもの

$$
X_i \leftarrow U \rightarrow X_j
$$


## 考察(辺の有無) {#discussion2}

2つの頂点間の矢線について

* ベイジアンネットワーク
  * 矢線がない:何らかの条件付き独立関係が成り立っている
  * 矢線がある:変数間に従属関係がある
* 因果ダイアグラム
  * 矢線がない:直接的な因果関係が存在しない
  * 矢線がある:直接的な因果関係or従属関係が存在する可能性を示す
  
* 「矢線が存在しない = 因果関係がない」ということを主張するためには強い根拠が必要
  * 3.4節で再度議論


## 考察(定常性) {#discussion3}

* $X_i = g_i(\text{pa}(X_i), \epsilon_i)$に含まれる各方程式は普遍的なもの
  * 特定の状況下で得られたものではない
  * 人間の主観的な理解に依存して変化することもない

* 例:サンゴの生存率と捕食者の個体密度
  * 捕食者がサンゴを捕食しているのを観測 = 捕食者の密度 $\rightarrow $ サンゴの生存率
  * もし捕食者が死にかけのサンゴしか食べないなら、サンゴの生存率 $\rightarrow$ 捕食者の密度
  * 後者が真の因果関係なら、前者はデータに基づく我々の主観的な理解

<div class="box">
定常性とは、データ生成過程が客観的な知識に基づいて記述されたものであり、
それが我々の主観的な理解と異なるからと言って、
データ生成過程が我々の主観的な理解と一致するように変化するわけではないことを保証するものである。
</div>

* うーん、深い…？


## 定常性と忠実性の違い {#stability_faithful}

* 定常性と忠実性は同義的に使われることは多いが、この本での定義は異なる
  * 定常性:定性的な因果関係に基づくもの(忠実性を満たさないものも含む)
  * 忠実性:条件付き独立関係とそれを表現したDAGに着目したもの
  
* 例:$ X \rightarrow Y $
  * 定常性の観点では、$Y$が$X$の原因となることはないことを意味している
    * 因果関係の有無や大きさをデータによって判断
  * 忠実性の観点では、$X$が$Y$に影響を与えている前提で、その影響の大きさが興味の対象


## 考察(自律性) {#discussion4}

* $X_i = g_i(\text{pa}(X_i), \epsilon_i)$に含まれる各方程式はモジュール
  * モジュール同士に依存関係がない
  * いくつかの構造方程式が変化したとしても、直接的には変化の対象となっていない構造方程式はそのまま
  * 直接的変化が起こった構造方程式だけを修正することで、変化に対応した因果モデルを構築できる
  * 3.5節で詳しく

* 因果関係を記述する数理モデルに柔軟性を与える仮定


## BNと因果ダイアグラムの思想の違い {#bn_causality}

* 2章の条件付き確率は、同時分布に基づいて定式化
* ベイジアンネットワークは、任意の変数順序でDAGを構築可能
  * 同時分布の近似、統計的独立関係の視覚的表現
  * (近似の良さなどを問わなければ)一意性がない

* 因果ダイアグラムは、データ生成過程を視覚的に表現したもの
  * 条件付き確率に基づいて同時分布を定式化
* 因果ダイアグラムは、データ生成過程が与えられたら一意に定まる
  * 因果ダイアグラムが与えられたら、定性的なデータ生成過程も一意に定まる(方程式の詳細はわからないけど)
  

# 確率・構造的因果モデル・物理モデル

## 確率と因果関係 {#causality_probability}

データを用いて因果関係を調べることが多い。この時どんなことに気をつけるべきか？

* まずは確率分布の考え方について

* データが採取された背景($K$)が存在していて、データは「$K$による条件付き」となっている
* 暗黙的に制約された背景の中で因果推論を行おうとしている


## 物理モデルと因果関係 {#causality_probability}

* 物理の方程式は対称的
* 一方で、「AがBを引き起こす」と「BがAを引きをこす」とを比較する時、1つの方程式の話をしているわけではない
* 因果モデルは3つの要素が追加されている
  * inとoutの区別(左辺が右辺で生成されている、両辺の入れ替えが発生するような式変形はNG)
  * 各方程式は独立したメカニズムに対応しているという仮定
  * 介入・自律性
* 例:気体の体積と圧力の関係を定式化したボイルの法則


## 大域的と局所的 {#macro_micro}

* 大域的な研究成果は、小さな研究成果の積み重ねと考えると、
  局所的世界で因果関係を議論するのは普通
  * ただし、不要な議論を避けるために、データが採取された背景や問題設定を明確にしておく
* 見かけ上同じ測定項目でも、どの粒度の現象に興味があるのかによって、扱う因果関係の問題は異なる
  * マクロ的な現象に興味があるのか？ミクロ的な現象に興味があるのか？
  

## 外的妥当性 {#external_validity}

* データが採取された状況とデータ解析結果を適用しようとする状況では、
  大なり小なり背景情報は異なる
  * RCTでも人種・性別・地域などの背景が異なれば結果が異なることは十分あり得る
  * 交互作用効果を適切に評価しよう！(詳しくは4.7節)

* ある集団で得られた結果が、別の集団でどの程度成り立つかという問題
  * 移設可能性(transportability)
  * 大域的に捉えると、一般化可能性(generalizability)や外的妥当性(external validity)
  * RCT最強と思わないでね？
  
  
# 矢線の解釈 {#interpretation_arrow}

## 矢線の解釈 {#arrow}

因果推論の観点から、グラフの矢線に対する直感的な解釈をやり直す(これまでは統計的独立関係の観点だった)

* $X \rightarrow Y$は、$X$が$Y$に対して直接的に影響を与える**可能性がある**と言っているだけ
  * データで評価して見たら、「直接的な因果関係はなかった」と判断される場合もある
* 因果ダイアグラムはデータ生成過程の定性的な性質を視覚的に表現しただけ
  * 矢線があっても、生成過程の詳細や、因果効果の強さは分からない
  * 矢線が無いと、定量的に評価しなくても直接的な因果関係がないことは確認できる(故に強い主張)
  * 統計的仮説検定の帰無仮説を考えるとわかりやすい
    * 帰無仮説が棄却されなくても、帰無仮説を積極的に採択するわけじゃない
    

# モジュール性と外的操作 {#module}

## 自律性の仮定 {#autonomous}

* 自律性を仮定するから、DAGを用いた因果推論が柔軟になる
  * 外的操作の対象となっている構造方程式だけを興味のある外的操作方程式に入れ替えればOK

* データ生成過程に基づく数理モデルは偉大
  * データ生成過程が反映されていない同時分布を使っても、条件付き確率に基づく予測しかできない
  * 自律性を仮定し、構造方程式モデルの構成要素をモジュールとみなせれば、
    介入を行ったときの反応の状態を数学的に取り扱える


## 介入(外的操作) {#intervention}

* 構造方程式モデルにおける外的操作とは、興味ある構造方程式を他の方程式に置き換えること
  * 3.16式と3.18式を見比べる
  * 外的操作を行う前の因果ダイアグラム:図3-2
  * 外的操作を行った後の因果ダイアグラム:図3-3(a)

* 確率変数の同時分布は、$\text{do}(X=x)$を使って書ける
  * 関数関係の置き換えという数学的操作
  * 「$X=x$または$x'$」のような選言的な外的操作を直接的には扱えない
    * No Multiple Versions of Treatmentが成り立たないケース
    * 処理水準内では異質性が存在しないという仮定(P13下)

## 介入と条件付けの違い {#intervention_conditioning}

* 条件付け(conditioning)
  * $X=x$が観察されている状況
  * 因果ダイアグラムそのものに変化はない

* 介入(外的操作, intervention)
  * 強制的に$X=x$に固定する
  * 元の因果ダイアグラムから介入対象の変数に向かう矢線をすべて取り除く


## 介入とRCT {#intervention_RCT}

* P87の内容
* 介入は強制的に確率1で値を固定するから、ランダム割付とは異なる？
  * 介入は、ある値に固定すること(原子的介入)だけじゃない
* RCTは、$X$に対応する構造方程式を確率$p^*(x_1)$で$X=x_1$を取り、
  確率$1-p^*(x_1)$で$X=x_0$を取るような確率変数に置き換える操作を考えれば良い
  * 同時分布は、3.22式で与えられる
  * 因果ダイアグラムは、$X$に向かう矢線が取り除かれた形式で記述

* RCTはdoオペレーターで定義される確率分布を直接求める研究デザイン


## doオペレーターの性質1 {#do_1}

<div class="box">
$X_i$を一定の値$x_i$に固定するという外的操作が確率1で行われるならば、以下が成り立つ

$$
p(x_i|\text{do}(X_i = x_i)) = 1
$$
</div>

## doオペレーターの性質2 {#do_2}

<div class="box">
$$
p(x_i | \text{do}(\text{pa}(X_i) = \text{pa}(x_i))) = p(x_i | \text{pa}(x_i))
$$

が成立する。
</div>

* $\text{pa}(X_i) = (X_{i,1}, \dots, X_{i,q})^\top$
* $\text{pa}(x_i) = (x_{i,1}, \dots, x_{i,q})^\top$
* $\text{do}(\text{pa}(X_i) = \text{pa}(x_i))$は、$(\text{do}(X_{i,1} = x_{i,1}), \dots, \text{do}(X_{i,q} = x_{i,q}))^\top$を意味する

* $X_i$の直接的原因集合$\text{pa}(X_i)$に外的操作を行ったときの$X_i$の確率分布は、$\text{pa}(X_i)$を与えた時の$X_i$の条件付き確率分布に等しい
  * 左辺は、$\text{pa}(X_i)$に向かう矢線を取り除いた因果ダイアグラム
  * 右辺は、因果ダイアグラムはそのままに$\text{pa}(X_i)$を条件つけただけ
  
  
## doオペレーターの性質3 {#do_3}

<div class="box">
$\{ X_i \} \cup \text{pa}(X_i)$と排反な任意の集合$\mathbf S$に対して、以下が成り立つ

$$
\begin{align}
p(&x_i | \text{do}(\text{pa}(X_i) = \text{pa}(x_i)), \text{do}(\mathbf S = \mathbf s)) \\
&= p(x_i | \text{do}(\text{pa}(X_i) = \text{pa}(x_i)) \\
&= p(x_i | \text{pa}(x_i))
\end{align}
$$
</div>

$X_i$の直接的原因$\text{pa}(X_i)$と$\mathbf S$の両方に外的操作を行ったときの$X_i$の確率分布は、
$\text{pa}(X_i)$のみに外的操作を行ったときの$X_i$の確率分布と等しい

また、性質2より、上記は$\text{pa}(X_i)$を与えたときの$X_i$の条件付き確率分布と等しい